version: '3.8'

services:
  sabre:
    image: sabre:latest
    build:
      context: .
    ports:
      - "25565:25565" # minecraft
      - "7270:7270" # resourcepack
    volumes:
      - ./extensions:/srv/extensions
      - ./sabre-config.json:/srv/sabre-config.json
    stdin_open: true
    tty: true